[project]
name = "insalubre-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "nextcord[speed]>=3,<4",
    "orjson>=3.10.15",
    "pynacl>=1.5.0",
    "sqlalchemy[asyncio]>=2,<3",
    "whatsapp-api-client-python>=0.0.49",
]

[tool.pyright]
include = [ "src", "migrations" ]
reportUnusedImport = false

[[tool.pyright.executionEnvironments]]
root = 'src/db'
reportUninitializedInstanceVariable = false
reportExplicitAny = false
reportDeprecated = false


[tool.ruff]
fix = true
respect-gitignore = true
line-length = 88
indent-width = 2
src = ["src", "migrations"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"src/__main__.py" = ["F401"]

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "single"

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

